CREATE TABLE `300049210finalusers` (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    role ENUM('user', 'admin') NOT NULL DEFAULT 'user'
);

CREATE TABLE `300049210finalnews` (
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    date DATETIME DEFAULT CURRENT_TIMESTAMP,
    uid INT,
    FOREIGN KEY (uid) REFERENCES `300049210finalusers` (id) ON DELETE SET NULL
);

CREATE TABLE `300049210finalprofilepic` (
    uid INT PRIMARY KEY,
    ppic VARCHAR(255),
    FOREIGN KEY (uid) REFERENCES `300049210finalusers` (id) ON DELETE CASCADE
);

CREATE TABLE `300049210finalproducts` (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    price DECIMAL(10,2) NOT NULL
    );

CREATE TABLE `300049210finalcart` (
    id INT AUTO_INCREMENT PRIMARY KEY,
    uid INT,
    pid INT,
    FOREIGN KEY (uid) REFERENCES `300049210finalusers` (id) ON DELETE CASCADE,
    FOREIGN KEY (pid) REFERENCES `300049210finalproducts` (id) ON DELETE CASCADE
    );

CREATE TABLE `300049210finalproductpic` (
    id INT PRIMARY KEY,
    pic VARCHAR(255) NOT NULL,
    FOREIGN KEY (id) REFERENCES `300049210finalproducts`(id) ON DELETE CASCADE
    );

CREATE TABLE `300049210finalpics` (
    id INT AUTO_INCREMENT PRIMARY KEY,
    pic VARCHAR(255) NOT NULL
    );